export const SET_LOADING = 'SET_LOADING';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const GET_CUSTOMER = 'GET_CUSTOMER';
export const PUT_CUSTOMER = 'PUT_CUSTOMER';

export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const ADD_ITEMS_CART = 'ADD_ITEMS_CART';
export const SUB_ITEMS_CART = 'SUB_ITEMS_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CHANGE_SHOW_CART = 'CHANGE_SHOW_CART';

export const GET_PRODUCT = 'GET_PRODUCT';

export const GET_SEARCHNAV_RESULTS = 'GET_SEARCHNAV_RESULTS';
export const GET_SEARCHPAGE_RESULTS = 'GET_SEARCHPAGE_RESULTS';

export const GET_ADDRESS = 'GET_ADDRESS';
export const POST_ADDRESS = 'POST_ADDRESS';
export const PUT_ADDRESS = 'PUT_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

export const POST_ORDER = 'POST_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER = 'GET_ORDER';
export const PUT_CANCEL_ORDER = 'PUT_CANCEL_ORDER';

export const GET_ERRORS = 'GET_ERRORS';
